//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaBox.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee : Person
    {
        public System.Guid OutletId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Position { get; set; }
        public double Wage { get; set; }
        public double WageType { get; set; }
        public string Status { get; set; }
    
        public virtual Outlet Outlet { get; set; }
    }
}
