//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaBox.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> OutletId { get; set; }
        public Nullable<System.Guid> PersonId { get; set; }
        public System.DateTime DateOrdered { get; set; }
        public string Items { get; set; }
        public double SubTotal { get; set; }
        public double Total { get; set; }
    
        public virtual Outlet Outlet { get; set; }
        public virtual Person Person { get; set; }
    }
}
